UrlShortenerInforceTestTask/Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using UrlShortenerInforceTestTask.Data;
using UrlShortenerInforceTestTask.Interfaces;
using UrlShortenerInforceTestTask.Models;
using UrlShortenerInforceTestTask.Utils;
using UrlShortenerInforceTestTask.ViewModels;

namespace UrlShortenerInforceTestTask.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAppUserRepository _appUserRepository;
        private readonly IConfiguration _config;

        public AuthController(IAppUserRepository appUserRepository, IConfiguration config)
        {
            _appUserRepository = appUserRepository;
            _config = config;
        }

        [HttpGet("Register")]
        public IActionResult Register()
        {
            var response = new RegisterViewModel();
            return View(response);
        }

        [HttpPost("Register")]
        public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
        {
            var firstName = registerViewModel.FirstName;
            var lastName = registerViewModel.LastName;
            var email = registerViewModel.EmailAddress;
            var password = PasswordHasher.HashPassword(registerViewModel.Password);

            if (!ModelState.IsValid) return View(registerViewModel);

            var user = await _appUserRepository.FindUserByEmailAsync(email);
            if (user != null)
            {
                TempData["Error"] = "This email address is already in use";
                return View(registerViewModel);
            }

            var newUser = new AppUser()
            {
                FirstName = registerViewModel.FirstName,
                LastName = registerViewModel.LastName,
                Email = email,
                Password = password
            };

            var newUserResponse = _appUserRepository.Add(newUser);
            if (newUserResponse)
                _appUserRepository.Save();
            else
            {
                TempData["Error"] = "Password should contain at least one digit, special character and uppercase symbol";
                return View(registerViewModel);
            }

            return RedirectToAction("ShortURLsTable", "Urls");
        }

        [HttpGet("Login")]
        public IActionResult Login()
        {
            var response = new LoginViewModel();
            return View(response);
        }

        [HttpPost("Login")]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid) return View(loginViewModel);

            var email = loginViewModel.EmailAddress;
            var password = loginViewModel.Password;

            var user = await _appUserRepository.FindUserByEmailAsync(email);

            if (user != null)
            {
                bool passwordCheck = PasswordHasher.HashPassword(loginViewModel.Password) == user.Password;
                if (passwordCheck)
                {
                    bool userRole = user.IsAdmin;
                    var claims = new List<Claim>() 
                    { 
                        new Claim("userId", user.Id.ToString()),
                        new Claim("email", email)                    
                    };
                    if (userRole)
                        claims.Add(new Claim("role", "admin"));
                    else
                        claims.Add(new Claim("role", "user"));

                    var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config.GetSection("Jwt:Key").Value));

                    var signingCred = new SigningCredentials(securityKey,
                        SecurityAlgorithms.HmacSha256);

                    var securityToken = new JwtSecurityToken(
                        claims: claims,
                        expires: DateTime.Now.AddMinutes(20),
                        issuer: _config.GetSection("Jwt:Issuer").Value,
                        audience: _config.GetSection("Jwt:Audience").Value,
                        signingCredentials: signingCred);

                    var tokenString = new JwtSecurityTokenHandler().WriteToken(securityToken);
                    HttpContext.Session.SetString("JWToken", tokenString);


                    return RedirectToAction("ShortURLsTable", "Urls");
                    
                }
                TempData["Error"] = "Wrong credentials. Please, check your password";
                return View(loginViewModel);
            }

            TempData["Error"] = "Wrong credentials. Please, check your email or password";
            return View(loginViewModel);
        }

        [HttpGet("Logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("ShortURLsTable", "Urls");
        }

    }
}

UrlShortenerInforceTestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UrlShortenerInforceTestTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UrlShortenerInforceTestTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Urls" asp-action="ShortURLsTable">Url Shortener</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Urls" asp-action="ShortURLsTable">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Urls" asp-action="About">About</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>               
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>